export const pets =
    {
        "data": [
            {
                "id": "1",
                "name": "Max",
                "species": "Dog",
                "breed": "Golden Retriever",
                "age": 8,
                "gender": "Male",
                "size": "Large",
                "color": "Golden",
                "description": "A playful and friendly pup who loves to cuddle and play fetch.",
                "adoptionStatus": "Adoptable",
                "location": "Oslo, Norway",
                "image": {
                    "url": "https://placedog.net/500/400?id=1",
                    "alt": "Golden Retriever sitting on couch",
                },
                "created": "2025-01-01T12:00:00.000Z",
                "updated": "2025-01-01T12:00:00.000Z",
                "owner": {
                    "name": "Anna Larsen",
                    "email": "anna@example.com",
                    "bio": "Animal lover and foster volunteer.",
                    "avatar": {
                        "url": "https://randomuser.me/api/portraits/women/44.jpg",
                        "alt": "Anna's avatar",
                    },
                    "banner": {
                        "url": "https://picsum.photos/seed/banner1/1200/300",
                        "alt": "Anna's profile banner",
                    },
                },
            },
            {
                "id": "2",
                "name": "Luna",
                "species": "Cat",
                "breed": "Siamese",
                "age": 2,
                "gender": "Female",
                "size": "Medium",
                "color": "Cream and Brown",
                "description": "A calm and curious cat who loves sunny windows and gentle pats.",
                "adoptionStatus": "Adoptable",
                "location": "Bergen, Norway",
                "image": {
                    "url": "https://placekitten.com/500/400",
                    "alt": "Siamese cat looking out the window",
                },
                "created": "2025-01-02T10:00:00.000Z",
                "updated": "2025-01-02T10:00:00.000Z",
                "owner": {
                    "name": "Pet Rescue Bergen",
                    "email": "rescue@bergenpets.no",
                    "bio": "Connecting loving homes with lovely pets.",
                    "avatar": {
                        "url": "https://randomuser.me/api/portraits/men/12.jpg",
                        "alt": "Rescue team avatar",
                    },
                    "banner": {
                        "url": "https://picsum.photos/seed/banner2/1200/300",
                        "alt": "Bergen pet rescue banner",
                    },
                },
            },
            {
                "id": "3",
                "name": "Charlie",
                "species": "Dog",
                "breed": "Beagle",
                "age": 4,
                "gender": "Male",
                "size": "Medium",
                "color": "Brown and White",
                "description": "Energetic and loyal, Charlie is great with kids and other dogs.",
                "adoptionStatus": "Adoptable",
                "location": "Trondheim, Norway",
                "image": {
                    "url": "https://placedog.net/500/400?id=3",
                    "alt": "Beagle standing in a park",
                },
                "created": "2025-01-03T09:30:00.000Z",
                "updated": "2025-01-03T09:30:00.000Z",
                "owner": {
                    "name": "Hilde Andersen",
                    "email": "hilde@trondheimpets.no",
                    "bio": "Dog trainer and adoption coordinator.",
                    "avatar": {
                        "url": "https://randomuser.me/api/portraits/women/28.jpg",
                        "alt": "Hilde's avatar",
                    },
                    "banner": {
                        "url": "https://picsum.photos/seed/banner3/1200/300",
                        "alt": "Hilde's pet banner",
                    },
                },
            },
            {
                "id": "4",
                "name": "Milo",
                "species": "Cat",
                "breed": "Maine Coon",
                "age": 1,
                "gender": "Male",
                "size": "Large",
                "color": "Gray",
                "description": "Fluffy and affectionate, Milo loves being around people and snuggling.",
                "adoptionStatus": "Adoptable",
                "location": "Stavanger, Norway",
                "image": {
                    "url": "https://placekitten.com/500/401",
                    "alt": "Large fluffy Maine Coon cat",
                },
                "created": "2025-01-04T11:00:00.000Z",
                "updated": "2025-01-04T11:00:00.000Z",
                "owner": {
                    "name": "Stavanger Pets",
                    "email": "info@stavangerpets.no",
                    "bio": "Non-profit helping pets find forever homes.",
                    "avatar": {
                        "url": "https://randomuser.me/api/portraits/men/19.jpg",
                        "alt": "Volunteer avatar",
                    },
                    "banner": {
                        "url": "https://picsum.photos/seed/banner4/1200/300",
                        "alt": "Pet rescue banner",
                    },
                },
            },
            {
                "id": "5",
                "name": "Bella",
                "species": "Dog",
                "breed": "Jack Russell Terrier",
                "age": 3,
                "gender": "Female",
                "size": "Small",
                "color": "White and Brown",
                "description": "Bella is full of energy, super smart, and loves to chase balls!",
                "adoptionStatus": "Adoptable",
                "location": "Kristiansand, Norway",
                "image": {
                    "url": "https://placedog.net/500/400?id=5",
                    "alt": "Jack Russell Terrier running",
                },
                "created": "2025-01-05T14:00:00.000Z",
                "updated": "2025-01-05T14:00:00.000Z",
                "owner": {
                    "name": "Kristin Moe",
                    "email": "kristin@adoptkrs.no",
                    "bio": "Pet mom and volunteer.",
                    "avatar": {
                        "url": "https://randomuser.me/api/portraits/women/33.jpg",
                        "alt": "Kristin's avatar",
                    },
                    "banner": {
                        "url": "https://picsum.photos/seed/banner5/1200/300",
                        "alt": "Kristiansand pet banner",
                    },
                },
            },
            {
                "id": "6",
                "name": "Shadow",
                "species": "Cat",
                "breed": "Black Domestic Shorthair",
                "age": 5,
                "gender": "Female",
                "size": "Medium",
                "color": "Black",
                "description": "Elegant and mysterious, Shadow is quiet and loves cozy corners.",
                "adoptionStatus": "Adoptable",
                "location": "Drammen, Norway",
                "image": {
                    "url": "https://placekitten.com/500/402",
                    "alt": "Black cat with bright eyes",
                },
                "created": "2025-01-06T17:00:00.000Z",
                "updated": "2025-01-06T17:00:00.000Z",
                "owner": {
                    "name": "Marius Pettersen",
                    "email": "marius@catrescue.no",
                    "bio": "Cat specialist and part-time writer.",
                    "avatar": {
                        "url": "https://randomuser.me/api/portraits/men/47.jpg",
                        "alt": "Marius' avatar",
                    },
                    "banner": {
                        "url": "https://picsum.photos/seed/banner6/1200/300",
                        "alt": "Cat rescue banner",
                    },
                },
            },
        ],
    };